### ISSUE TITLE
Implement `all` and `-A` options to relevant commands

### ISSUE THREAD

**Issue by yokaze** [cybozu-go/network-policy-viewer#21]
## Motivation

Currently, several commands lack an option to list all the pods and namespaces.
For example:
- `npv dump`, `npv inspect`, and `npv list`: requires a pod name
- `npv id`: requires a namespace name

It is beneficial to list everything with an appropriate option.

## How

- `all` can be used instead of a pod name
- `-A` or `--all-namespaces` can be used instead of a namespace name
- Additional `name` or `namespace` lane will appear only when these flags are specified

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

## Tasks
- https://github.com/cybozu-go/network-policy-viewer/pull/34
- https://github.com/cybozu-go/network-policy-viewer/pull/37
